package asus.com.bwie.day1226lx.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import asus.com.bwie.day1226lx.bean.GreenShop;

import asus.com.bwie.day1226lx.dao.GreenShopDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig greenShopDaoConfig;

    private final GreenShopDao greenShopDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        greenShopDaoConfig = daoConfigMap.get(GreenShopDao.class).clone();
        greenShopDaoConfig.initIdentityScope(type);

        greenShopDao = new GreenShopDao(greenShopDaoConfig, this);

        registerDao(GreenShop.class, greenShopDao);
    }
    
    public void clear() {
        greenShopDaoConfig.clearIdentityScope();
    }

    public GreenShopDao getGreenShopDao() {
        return greenShopDao;
    }

}
