package asus.com.bwie.day1226lx.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import asus.com.bwie.day1226lx.bean.GreenShop;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GREEN_SHOP".
*/
public class GreenShopDao extends AbstractDao<GreenShop, Long> {

    public static final String TABLENAME = "GREEN_SHOP";

    /**
     * Properties of entity GreenShop.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Pid = new Property(0, long.class, "pid", true, "_id");
        public final static Property Price = new Property(1, double.class, "price", false, "PRICE");
        public final static Property Title = new Property(2, String.class, "title", false, "TITLE");
        public final static Property Images = new Property(3, String.class, "images", false, "IMAGES");
    }


    public GreenShopDao(DaoConfig config) {
        super(config);
    }
    
    public GreenShopDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GREEN_SHOP\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: pid
                "\"PRICE\" REAL NOT NULL ," + // 1: price
                "\"TITLE\" TEXT," + // 2: title
                "\"IMAGES\" TEXT);"); // 3: images
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GREEN_SHOP\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GreenShop entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getPid());
        stmt.bindDouble(2, entity.getPrice());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        String images = entity.getImages();
        if (images != null) {
            stmt.bindString(4, images);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GreenShop entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getPid());
        stmt.bindDouble(2, entity.getPrice());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        String images = entity.getImages();
        if (images != null) {
            stmt.bindString(4, images);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public GreenShop readEntity(Cursor cursor, int offset) {
        GreenShop entity = new GreenShop( //
            cursor.getLong(offset + 0), // pid
            cursor.getDouble(offset + 1), // price
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // title
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // images
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GreenShop entity, int offset) {
        entity.setPid(cursor.getLong(offset + 0));
        entity.setPrice(cursor.getDouble(offset + 1));
        entity.setTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setImages(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(GreenShop entity, long rowId) {
        entity.setPid(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(GreenShop entity) {
        if(entity != null) {
            return entity.getPid();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(GreenShop entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
